### ISSUE TITLE
Analyze stock management

### ISSUE THREAD

**Issue by EveCrystali** [EveCrystali/P3_Testez_implementation_fonctionnalite#28]
### Étape 4 : Comprenez la façon dont est géré l’inventaire - (50 % progression)

- _Avant de démarrer cette étape, je dois avoir : une compréhension du code existant et des modifications nécessaires à apporter pour compléter les TODO des notes de Louis._
- _Une fois cette étape terminée, je devrais avoir une compréhension du fonctionnement de la gestion de l'inventaire et des critères de validation pour les produits._

### TODO - Recommandations :

- [ ] comment les produits sont gérés dans l'application ;

- [ ] quels sont les critères de validation pour l'ajout ou la modification d'un produit dans l'inventaire.
- [ ] Étudiez la façon dont l’inventaire est géré en parcourant l’application dans le Front-End, et également en analysant les tables dans SSMS.
- [ ] Essayez de comprendre comment cette gestion de l’inventaire est mise en œuvre dans le code actuel (quelles règles sont imposées sur ce que l’utilisateur entre dans les champs).
- [ ] Identifiez les parties du code qui gèrent l'inventaire (grâce aux différentes
fonctions, en ajoutant des points d’arrêt pour déboguer, par exemple).
